### ISSUE TITLE
Error in  "chalk": "^4.0.0"

### ISSUE THREAD

**Issue by jasonmacer** [starak/node-console-stamp#44]
I am getting the following error when trying to use the latest 4.0.0 version. I have even rolled back and am getting the same issue.

node_modules\chalk\source\templates.js:115
                                throw new Error('Found extraneous } in Chalk template literal');
                                ^
Error: Found extraneous } in Chalk template literal
    at O:\XXXXXX\node_modules\chalk\source\templates.js:115:11
    at String.replace (<anonymous>)
    at module.exports (O:\XXXXXX\node_modules\chalk\source\templates.js:105:12)
    at chalkTag (O:\XXXXXX\node_modules\chalk\source\index.js:212:9)
    at chalk.template (O:\XXXXXX\node_modules\chalk\source\index.js:40:38)
    at msg (O:\XXXXXX\server.js:14:25)
    at O:\XXXXXX\node_modules\console-stamp\lib\utils.js:49:27
    at String.replace (<anonymous>)
    at O:\XXXXXX\node_modules\console-stamp\lib\utils.js:48:29
    at Array.forEach (<anonymous>)

Here is my actual code:

const chalk = require('chalk');
const lMap = {
    //log: chalk.hex('#183e69'),
    log: '',
    error: 'red',
    info: 'blue',
    warn: 'yellow',
    debug: 'cyan'
}
require('console-stamp')(console, {
    format: '(#).yellow :date(yy-mm-dd HH:MM:ss.l).green (#).yellow :msg',
    tokens: {
        msg: ( { method, msg } ) => {
            return chalk`{${lMap[method] || 'reset'} ${msg}}`;
        }
    }
});

global.Log = console.log.bind(console);
global.ILog = console.info.bind(console);
global.WLog = console.warn.bind(console);
global.ELog = console.error.bind(console);
global.DLog = console.debug.bind(console);

Has anyone else run into this issue.

**Comment by jasonmacer** [comment]
I'm so sorry! I Copy/Pasted in the wrong tab. If you can delete this, please do!

Again, I'm sorry!
